sudo: required
after_success:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client
  - sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$saurabh.joshi25"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$1/7c32a277b81a628a4f3192e21e84ce4b5c458e7f"$'\n' > ~/.transifexrc
  - tx push -s
